name: Build APK and IPA

on:
  push:
    branches:
      - master # 订阅 master 分支的提交
    tags:
      - '*'    # 订阅所有标签的创建或更新
  pull_request:
    branches:
      - master # 如果需要在 PR 合并到 master 之前运行构建，保持这一行
  workflow_dispatch: # 允许手动触发工作流

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    outputs:
      flutter-version: ${{ steps.setup-flutter.outputs.version }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
    - name: Set up Flutter
      id: setup-flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'

  build-apk:
    name: Build APK
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'
    - name: Install dependencies
      run: flutter pub get
    - name: Build APK
      run: flutter build apk --release
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk

  build-ipa:
    name: Build IPA
    needs: setup
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'
    - name: Install dependencies
      run: flutter pub get
    - name: Build IPA
      run: flutter build ipa --release
    - name: Upload IPA Artifact
      uses: actions/upload-artifact@v3
      with:
        name: release-ipa
        path: build/ios/ipa/*.ipa
