name: Build APK and iOS Packages

on:
  push:
    branches:
      - master
    tags:
      - 'v*' # 订阅 v* 格式的 tag，如 v1.0.0
  pull_request:
    branches:
      - master

jobs:
  build-apk:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Install dependencies
        run: |
          flutter pub get

      - name: Build APK
        run: |
          flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: build/app/outputs/flutter-apk/app-release.apk

  build-ios:
    name: Build iOS
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Install dependencies
        run: |
          flutter pub get

      - name: Build iOS
        run: |
          flutter build ios --release --no-codesign

      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios
          path: build/ios/iphoneos/Runner.app

  notify:
    name: Notify on success or failure
    runs-on: ubuntu-latest
    needs: [build-apk, build-ios]
    if: always()

    steps:
      - name: Send success/failure message
        run: echo "Build completed successfully for APK and iOS."
